### ISSUE TITLE
Exception in thread "Thread-0"

### ISSUE THREAD

**Issue by ghost** [mkorthof/ost2pst#3]
Hi,

Thanks a lot for your program.
I tried to use it on an Outlook 2016 OST file but it did not work. I know you wrote this is not supported, but I noticed you updated the program with apose.email 18.8... And since Outlook 2013/2016 files are supported since version 6.2.0... I gave it a try.

It finds the root folders and "converts" the file (it's more a copy than a conversion since the header does not change between OST and PST files. And the data remains the same to.

The process shows those errors : 

```
Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented
com.aspose.email.akm$b.a(SourceFile:3925)
com.aspose.email.akm.a(SourceFile:824)
com.aspose.email.akm.a(SourceFile:620)
com.aspose.email.wk.b(SourceFile:349)
com.aspose.email.acy.a(SourceFile:1774)
com.aspose.email.acy.b(SourceFile:733)
com.aspose.email.ape.a(SourceFile:893)
com.aspose.email.ape.b(SourceFile:1192)
com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:70)
java.lang.Thread.run(Unknown Source)
        at com.aspose.email.akm$b.a(SourceFile:3925)
        at com.aspose.email.akm.a(SourceFile:824)
        at com.aspose.email.akm.a(SourceFile:620)
        at com.aspose.email.wk.b(SourceFile:349)
        at com.aspose.email.acy.a(SourceFile:1774)
        at com.aspose.email.acy.b(SourceFile:733)
        at com.aspose.email.ape.a(SourceFile:893)
        at com.aspose.email.ape.b(SourceFile:1192)
        at com.aspose.email.PersonalStorage.convertTo(SourceFile:540)
        at com.aspose.email.PersonalStorage.saveAs(SourceFile:454)
        at com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:70)
        at java.lang.Thread.run(Unknown Source)
```

Could you help me ?

Thank you :)

**Comment by mkorthof** [comment]
Hey, the API doenst support it, see also:
#1  #2
