### ISSUE TITLE
Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented

### ISSUE THREAD

**Issue by jdschuitemaker** [mkorthof/ost2pst#4]
First the conversion seems to run nicely, but somewhere near the end I get this error message: Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented

```
OST2PST (200119)

INFO: Loading OST file "j@j.com - Copy.ost" (2GB)
      Folder [00] "Root - Public"
      Folder [01] "Root - Mailbox"

INFO: Converting "j@j.com - Copy.ost" to "j@j.com - Copy.pst"
      1749MB/1749MB (100%) O
Exception in thread "Thread-0" class com.aspose.email.system.exceptions.NotImplementedException: The method or operation is not implemented
com.aspose.email.zany$zb.a(SourceFile:3933)
com.aspose.email.zany.a(SourceFile:824)
com.aspose.email.zany.a(SourceFile:620)
com.aspose.email.zxk.c(SourceFile:346)
com.aspose.email.zafo.a(SourceFile:1774)
com.aspose.email.zafo.b(SourceFile:735)
com.aspose.email.zatg.a(SourceFile:940)
com.aspose.email.zatg.b(SourceFile:1239)
com.aspose.email.PersonalStorage.convertTo(SourceFile:514)
com.aspose.email.PersonalStorage.saveAs(SourceFile:428)
com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:83)
java.lang.Thread.run(Unknown Source)
        at com.aspose.email.zany$zb.a(SourceFile:3933)
        at com.aspose.email.zany.a(SourceFile:824)
        at com.aspose.email.zany.a(SourceFile:620)
        at com.aspose.email.zxk.c(SourceFile:346)
        at com.aspose.email.zafo.a(SourceFile:1774)
        at com.aspose.email.zafo.b(SourceFile:735)
        at com.aspose.email.zatg.a(SourceFile:940)
        at com.aspose.email.zatg.b(SourceFile:1239)
        at com.aspose.email.PersonalStorage.convertTo(SourceFile:514)
        at com.aspose.email.PersonalStorage.saveAs(SourceFile:428)
        at com.ost2pst.LoadAndConvertOSTFileCLI$1.run(LoadAndConvertOSTFileCLI.java:83)
        at java.lang.Thread.run(Unknown Source)
```

Any idea what could be happening?

**Comment by jdschuitemaker** [comment]
Never mind, I now see that you do not support OST files from Outlook 2016
